// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// OP
List OP(std::vector<double> data, double penalty);
RcppExport SEXP _svpChange2_OP(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(OP(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// PELT
List PELT(std::vector<double> data, double penalty);
RcppExport SEXP _svpChange2_PELT(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(PELT(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// SN
List SN(std::vector<double> data, int Kmax);
RcppExport SEXP _svpChange2_SN(SEXP dataSEXP, SEXP KmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type Kmax(KmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(SN(data, Kmax));
    return rcpp_result_gen;
END_RCPP
}
// focus_valid_cpp
bool focus_valid_cpp(std::vector<double> data, double gamma, bool check_all_prefixes);
RcppExport SEXP _svpChange2_focus_valid_cpp(SEXP dataSEXP, SEXP gammaSEXP, SEXP check_all_prefixesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type check_all_prefixes(check_all_prefixesSEXP);
    rcpp_result_gen = Rcpp::wrap(focus_valid_cpp(data, gamma, check_all_prefixes));
    return rcpp_result_gen;
END_RCPP
}
// SVP
List SVP(std::vector<double> data, double gamma, std::string test, bool prune_after_if_unvalid, bool prune_before_if_invalid, bool use_multiscale_gamma, double sigma2, double q_alpha_n, double rho, bool profile_sigma, double quantile);
RcppExport SEXP _svpChange2_SVP(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_after_if_unvalidSEXP, SEXP prune_before_if_invalidSEXP, SEXP use_multiscale_gammaSEXP, SEXP sigma2SEXP, SEXP q_alpha_nSEXP, SEXP rhoSEXP, SEXP profile_sigmaSEXP, SEXP quantileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_after_if_unvalid(prune_after_if_unvalidSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_before_if_invalid(prune_before_if_invalidSEXP);
    Rcpp::traits::input_parameter< bool >::type use_multiscale_gamma(use_multiscale_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type q_alpha_n(q_alpha_nSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type profile_sigma(profile_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type quantile(quantileSEXP);
    rcpp_result_gen = Rcpp::wrap(SVP(data, gamma, test, prune_after_if_unvalid, prune_before_if_invalid, use_multiscale_gamma, sigma2, q_alpha_n, rho, profile_sigma, quantile));
    return rcpp_result_gen;
END_RCPP
}
// svp0
List svp0(std::vector<double> data, double gamma, Function test, bool prune_after_if_unvalid, bool prune_if_PELT);
RcppExport SEXP _svpChange2_svp0(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_after_if_unvalidSEXP, SEXP prune_if_PELTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Function >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_after_if_unvalid(prune_after_if_unvalidSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_PELT(prune_if_PELTSEXP);
    rcpp_result_gen = Rcpp::wrap(svp0(data, gamma, test, prune_after_if_unvalid, prune_if_PELT));
    return rcpp_result_gen;
END_RCPP
}
// AR1_rho
double AR1_rho(std::vector<double> data);
RcppExport SEXP _svpChange2_AR1_rho(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(AR1_rho(data));
    return rcpp_result_gen;
END_RCPP
}
// AR1_single_change
List AR1_single_change(std::vector<double> data, double gamma, double rho, double sigma2, bool profile_sigma);
RcppExport SEXP _svpChange2_AR1_single_change(SEXP dataSEXP, SEXP gammaSEXP, SEXP rhoSEXP, SEXP sigma2SEXP, SEXP profile_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type profile_sigma(profile_sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(AR1_single_change(data, gamma, rho, sigma2, profile_sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_svpChange2_OP", (DL_FUNC) &_svpChange2_OP, 2},
    {"_svpChange2_PELT", (DL_FUNC) &_svpChange2_PELT, 2},
    {"_svpChange2_SN", (DL_FUNC) &_svpChange2_SN, 2},
    {"_svpChange2_focus_valid_cpp", (DL_FUNC) &_svpChange2_focus_valid_cpp, 3},
    {"_svpChange2_SVP", (DL_FUNC) &_svpChange2_SVP, 11},
    {"_svpChange2_svp0", (DL_FUNC) &_svpChange2_svp0, 5},
    {"_svpChange2_AR1_rho", (DL_FUNC) &_svpChange2_AR1_rho, 1},
    {"_svpChange2_AR1_single_change", (DL_FUNC) &_svpChange2_AR1_single_change, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_svpChange2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
