#include "svp_internal.h"
#include "svp_ar1_helpers.h"
#include <Rcpp.h>
#include <vector>
#include <algorithm>
#include <cmath>
#include <string>

using namespace Rcpp;

// -----------------------------------------------------------------------------
// Test dispatch
// -----------------------------------------------------------------------------

namespace {

// Names accepted by the public SVP() dispatcher.
enum class TestKind {
  GaussianMean,
  GammaRate,
  GaussianVariance,
  Quantile,
  QuantileExact,
  VarCost,
  WilcoxonCost,
  MedianMoodCost,
  AR1,
  AR1Profile,
  AR1Focus
};

// Convert the user-facing test name to the corresponding internal enum value.
TestKind parse_test_kind(const std::string& test)
{
  if (test == "gaussian_mean") return TestKind::GaussianMean;
  if (test == "gamma_rate") return TestKind::GammaRate;
  if (test == "gaussian_variance") return TestKind::GaussianVariance;
  if (test == "quantile") return TestKind::Quantile;
  if (test == "quantileExact") return TestKind::QuantileExact;
  if (test == "varCost") return TestKind::VarCost;
  if (test == "WilcoxonCost") return TestKind::WilcoxonCost;
  if (test == "MedianMoodCost") return TestKind::MedianMoodCost;
  if (test == "AR1") return TestKind::AR1;
  if (test == "AR1Profile") return TestKind::AR1Profile;
  if (test == "AR1Focus") return TestKind::AR1Focus;

  stop("Unknown test type: '%s'.", test.c_str());
  return TestKind::GaussianMean;
}

} // namespace

// -----------------------------------------------------------------------------
// Public SVP API
// -----------------------------------------------------------------------------

//' Smallest Valid Partitioning with Incremental Validity Tests
//'
//' Segments a univariate series into the smallest number of segments that pass
//' a selected validity test. Among partitions with the same number of segments,
//' the function chooses the one with the smallest within-segment squared-error
//' cost. The validity statistics are maintained incrementally in C++, so this
//' interface is considerably faster than supplying an R validity function to
//' [svp0()].
//'
//' A candidate segment is evaluated at its current endpoint. The
//' `gaussian_mean` test uses the FOCUS statistic at that endpoint, as do the
//' other built-in tests. Whether an invalid endpoint can be reconsidered at a
//' later endpoint depends on `subtests`: with `subtests = "none"`, the
//' candidate is retained and can recover; with `subtests = "right"` or
//' `subtests = "both"`, it is removed immediately and cannot recover. With
//' `subtests = "left"`, it can also be removed by the left-pruning rule when a
//' later candidate fails. The available values of `test` are:
//'
//' * `"gaussian_mean"`: Gaussian FOCUS likelihood-ratio test for a change in
//'   mean. Use this for independent Gaussian observations with constant
//'   variance.
//' * `"gamma_rate"`: likelihood-ratio test for a change in the rate of
//'   positive Gamma observations (unit shape in the current implementation).
//' * `"gaussian_variance"`: Gamma-rate test applied to squared observations,
//'   for changes in Gaussian variance around a known zero mean.
//' * `"AR1"`: exact fixed-`rho` Gaussian likelihood-ratio scan for a change in
//'   the marginal mean of an AR(1) series. In the AR(1) model, an innovation is
//'   the new random shock after accounting for the previous observation and the
//'   AR(1) mean structure; `sigma2` is the variance of this shock, not the
//'   marginal variance of the observations.
//' * `"AR1Profile"`: the same exact AR(1) scan, but profiling out the innovation
//'   variance. The variance is estimated separately under the no-change and
//'   change models from their residual sums of squares, which is useful when
//'   the innovation scale is unknown.
//' * `"AR1Focus"`: faster approximate AR(1) test that applies Gaussian FOCUS
//'   to the innovations `x[t] - rho * x[t - 1]`. The exact `"AR1"` test is the
//'   preferred choice when boundary accuracy matters.
//'
//' For an AR(1) series generated by `ts_generator(type = "gaussAR1")`, the
//' model is `x[t] = mu[t] + e[t]`, with
//' `e[t] = rho * e[t - 1] + eta[t]` and
//' `eta[t] ~ N(0, sigma2)`. Thus, `rho` controls serial dependence and
//' `sigma2` is the innovation variance, that is, the variance of the new shock
//' after accounting for the previous observation. It is not the marginal
//' variance of the observed series; for a stationary AR(1) noise process, the
//' marginal variance is `sigma2 / (1 - rho^2)`. In `ts_generator()`,
//' `sd_noise` is the innovation standard deviation, so use
//' `sigma2 = sd_noise^2`.
//'
//' `"AR1"` treats `rho` and `sigma2` as fixed and uses the exact conditional
//' Gaussian likelihood scan. `"AR1Profile"` uses the same exact scan but
//' estimates the innovation variance separately under the no-change and
//' change models. This is useful when the innovation scale is unknown.
//' `"AR1Focus"` is faster because it applies the Gaussian FOCUS calculation
//' to the transformed innovations; it is an approximation and can produce
//' different boundaries near a change point.
//'
//' The "subtests" argument selects the validity-based candidate-pruning rules.
//' "right" removes a candidate boundary when its segment becomes invalid;
//' "left" removes older candidate boundaries when a later candidate fails;
//' "both" applies both rules; and "none" retains all candidates. Validity is
//' still checked in every mode, and invalid candidates are never used.
//' Pruning is exact only when the selected validity test has the corresponding
//' monotonicity properties. For an arbitrary user-defined rule, use
//' "none" unless those properties have been established.
//'
//' @param data Numeric vector containing the univariate series. Missing or
//'   non-finite values are not supported.
//' @param gamma Positive finite scalar validity threshold. A larger value
//'   generally accepts longer or less homogeneous segments.
//' @param test Character scalar selecting one of the validity tests listed in
//'   Details. Defaults to `"gaussian_mean"`.
//' @param subtests Character scalar selecting the validity-pruning rules:
//'   "both" (default), "right", "left", or "none".
//' @param sigma2 Positive finite innovation variance for the exact AR1 tests.
//'   It is the conditional/error variance of the new AR(1) shock, not the
//'   marginal variance of the observed series. It is used when the variance is
//'   fixed; it is not used to form the profiled statistic.
//' @param rho AR(1) coefficient for the three AR1 tests. It must be finite and
//'   strictly between -1 and 1. If it is `NA`, the value is estimated robustly
//'   from the full series using [AR1_rho()].
//' @param profile_sigma Logical; if `TRUE`, estimate the innovation variance
//'   separately under the no-change and one-change AR(1) models when
//'   `test = "AR1"`. This removes the need to know the innovation scale and
//'   uses the resulting residual sums of squares in the likelihood-ratio
//'   statistic. Using `test = "AR1Profile"` has the same effect. The argument
//'   is ignored by other tests.
//' @param quantile Quantile level used by `"quantile"` and
//'   `"quantileExact"`. It is ignored by other tests.
//'
//' @return A list with "changepoints" (the inclusive end of every segment,
//'   including "length(data)"), "lastIndexSet" (zero-based candidate boundaries
//'   remaining at termination, in decreasing order), "nb" (the number of
//'   active candidates at the beginning of each endpoint iteration, before
//'   pruning), "costQ" (always "NULL"), and "R". Row "t" of matrix "R"
//'   stores the best cumulative squared-error cost, number of segments, and
//'   previous boundary for "data[1:t]".
//'
//' @examples
//' # Gaussian mean: FOCuS test for independent Gaussian observations.
//' set.seed(1)
//' gaussian_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(0, 2, -1),
//'   sd_noise = 1, type = "gauss"
//' )
//' SVP(gaussian_data, gamma = 2 * log(length(gaussian_data)),
//'     test = "gaussian_mean")$changepoints
//'
//' # Gamma rate: positive exponential observations with changing rates.
//' gamma_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(1, 4, 2),
//'   type = "exp"
//' )
//' SVP(gamma_data, gamma = 2 * log(length(gamma_data)),
//'     test = "gamma_rate")$changepoints
//'
//' # Gaussian variance: parameters are segment standard deviations.
//' variance_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(0.5, 1.5, 0.75),
//'   type = "variance"
//' )
//' SVP(variance_data, gamma = 2 * log(length(variance_data)),
//'     test = "gaussian_variance")$changepoints
//'
//' # Quantile and exact quantile tests: robust tests for changes in spread.
//' quantile_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(0.5, 1.5, 0.75),
//'   type = "variance"
//' )
//' SVP(quantile_data, gamma = 2, quantile = 0.1,
//'     test = "quantile")$changepoints
//' SVP(quantile_data, gamma = 2, quantile = 0.1,
//'     test = "quantileExact")$changepoints
//'
//' # Robust variance, Wilcoxon, and Median-Mood tests.
//' robust_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(0, 2, -1),
//'   sd_noise = 1, type = "gauss"
//' )
//' SVP(robust_data, gamma = 2, test = "varCost")$changepoints
//' SVP(robust_data, gamma = 2 * log(length(robust_data)),
//'     test = "WilcoxonCost")$changepoints
//' SVP(robust_data, gamma = 2 * log(length(robust_data)),
//'     test = "MedianMoodCost")$changepoints
//'
//' # Exact AR(1), with the known innovation variance.
//' ar1_data <- ts_generator(
//'   chpts = c(20, 40, 60), parameters = c(0, 2, -1),
//'   sd_noise = 0.8, rho = 0.7, type = "gaussAR1"
//' )
//' SVP(ar1_data, gamma = 2 * log(length(ar1_data)), test = "AR1",
//'     rho = 0.7, sigma2 = 0.8^2)$changepoints
//'
//' # Exact AR(1) with the innovation variance profiled out.
//' SVP(ar1_data, gamma = 2 * log(length(ar1_data)),
//'     test = "AR1Profile", rho = 0.7, sigma2 = 1)$changepoints
//'
//' # Faster approximate AR(1) FOCUS test on the transformed innovations.
//' SVP(ar1_data, gamma = 2 * log(length(ar1_data)),
//'     test = "AR1Focus", rho = 0.7, sigma2 = 0.8^2)$changepoints
//'
//' @seealso [svp0()] for arbitrary R validity functions, [AR1_rho()], and
//'   [AR1_single_change()].
//' @export
// [[Rcpp::export]]
List SVP(std::vector<double> data,
         double gamma,
         std::string test = "gaussian_mean",
         std::string subtests = "both",
         double sigma2 = 1.0,
         double rho = NA_REAL,
         bool profile_sigma = false,
         double quantile = 0.01)
{
  if (data.empty()) {
    stop("'data' must contain at least one observation.");
  }

  if (!std::all_of(data.begin(), data.end(),
                   [](double value) { return std::isfinite(value); })) {
    stop("'data' must contain only finite observations.");
  }

  if (!std::isfinite(gamma) || gamma <= 0.0) {
    stop("gamma must be finite and positive");
  }

  const TestKind test_kind = parse_test_kind(test);

  if (subtests != "both" && subtests != "right" &&
      subtests != "left" && subtests != "none") {
    stop("'subtests' must be one of 'both', 'right', 'left', or 'none'.");
  }

  if ((test_kind == TestKind::Quantile ||
       test_kind == TestKind::QuantileExact) &&
      (!std::isfinite(quantile) || quantile <= 0.0 || quantile > 0.5)) {
    stop("quantile must be finite and in (0, 0.5]");
  }

  if (test_kind == TestKind::GammaRate &&
      !std::all_of(data.begin(), data.end(),
                   [](double value) { return value > 0.0; })) {
    stop("'data' must be strictly positive for test 'gamma_rate'.");
  }

  switch (test_kind) {
  case TestKind::GaussianMean:
    return svp_detail::svp_impl<GaussianMean>(data, gamma, subtests);
  case TestKind::GammaRate:
    return svp_detail::svp_impl<GammaRate>(data, gamma, subtests);
  case TestKind::GaussianVariance:
    return svp_detail::svp_impl<GaussianVariance>(data, gamma, subtests);
  case TestKind::QuantileExact:
    return svp_detail::svp_impl<QuantileCostExact>(
      data, gamma, subtests, quantile
    );
  case TestKind::Quantile:
    return svp_detail::svp_impl<QuantileCost>(
      data, gamma, subtests, quantile
    );
  case TestKind::VarCost:
    return svp_detail::svp_impl<varCost>(data, gamma, subtests);
  case TestKind::WilcoxonCost:
    return svp_detail::svp_impl<WilcoxonCost>(data, gamma, subtests);
  case TestKind::MedianMoodCost:
    return svp_detail::svp_impl<MedianMoodCost>(data, gamma, subtests);
  case TestKind::AR1:
  case TestKind::AR1Profile:
  case TestKind::AR1Focus: {
    if (!std::isfinite(sigma2) || sigma2 <= 0.0) {
      stop("sigma2 must be finite and positive");
    }
    const double rho_used = NumericVector::is_na(rho) ?
      svp_detail::robust_ar1_rho(data) : rho;
    if (!std::isfinite(rho_used) || std::fabs(rho_used) >= 1.0)
      stop("rho must be finite and strictly between -1 and 1");
    if (test_kind == TestKind::AR1Focus) {
      List result = svp_detail::svp_impl<AR1MeanChange>(
        data,
        gamma,
        subtests,
        rho_used,
        sigma2
      );
      result["rho"] = rho_used;
      result["sigma2"] = sigma2;
      return result;
    }
    List result = svp_detail::svp_impl<AR1ExactMeanChange>(
      data,
      gamma,
      subtests,
      rho_used,
      sigma2,
      test_kind == TestKind::AR1Profile || profile_sigma
    );
    result["rho"] = rho_used;
    result["sigma2"] = sigma2;
    return result;
  }
  }

  stop("Internal error while selecting the SVP test.");
}
