# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Optimal Partitioning Algorithm
#'
#' @title Optimal Partitioning Algorithm
#' @description This function implements the OP algorithm of a given vector `data` with a given penalty term.
#' It finds the optimal change points that minimize a penalized cost using dynamic programming.
#'
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#'
#' @return A list with (1) the `\code{changepoints}` elements, (2) a vector `\code{nb}` saving the number of non-pruned elements at each iteration, (3) a vector `\code{lastIndexSet}` containing the non-pruned indices at the end of the algo and (4) a vector `\code{costQ}` saving the optimal cost at each time step. The elements `\code{nb}` and `\code{lastIndexSet}` are set to NULL. They are included for consistency with other algorithms that prune the number of indices to be tracked over time.
#'
#' @examples
#' n <- 1000
#' data <- rep(c(0, 1, -0.5, 0), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' OPres <- OP(data, penalty)
#' OPres$changepoints
#'
#' @export
OP <- function(data, penalty) {
    .Call(`_svpChange2_OP`, data, penalty)
}

#' Optimal Partitioning algorithm using PELT
#'
#' @title Optimal Partitioning using PELT
#'
#' @description This function implements the OP algorithm using PELT of a given vector `data` with a given penalty term.
#' It finds the optimal change points that minimize the cost function using dynamic programming.
#'
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#'
#' @return A list with the following elements:
#' \itemize{
#'   \item \code{changepoints}: the last index of each segment,
#'   \item \code{nb}: a vector saving the number of non-pruned elements at each iteration,
#'   \item \code{lastIndexSet}: a vector containing the non-pruned indices at the end of the algorithm,
#'   \item \code{costQ}: a vector saving the optimal cost at each time step.
#' }
#' @examples
#' n <- 1000
#' data <- rep(c(0, 1, -0.5, 0), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' resPELT <- PELT(data, penalty)
#'
#' @export
PELT <- function(data, penalty) {
    .Call(`_svpChange2_PELT`, data, penalty)
}

#' Segment Neighborhood
#'
#' @title Segment Neighborhood
#'
#' @description This function implements the SN algorithm of a given vector `data` with a given maximum number of changes
#' It finds the optimal segmentation for all K between 1 and Kmax that minimizes the global cost using dynamic programming.
#'
#' @param data A numeric vector representing the data to segment.
#' @param Kmax An integer value representing the maximal number of segment
#'
#' @return A list with the following elements:
#' \itemize{
#'   \item \code{changepoints}: the last index of each segment for each number of segment K between 1 and Kmax
#'   \item \code{nb}: NULL
#'   \item \code{lastIndexSet}: NULL
#'   \item \code{costQ}: a matrix saving the optimal cost at each time step for each number of segments (in k-th column for k segments)
#' }
#'
#' @export
SN <- function(data, Kmax) {
    .Call(`_svpChange2_SN`, data, Kmax)
}

.focus_valid_cpp <- function(data, gamma, check_all_prefixes = TRUE) {
    .Call(`_svpChange2_focus_valid_cpp`, data, gamma, check_all_prefixes)
}

#' Smallest Valid Partitioning with Incremental Validity Tests
#'
#' Segments a univariate series into the smallest number of segments that pass
#' a selected validity test. Among partitions with the same number of segments,
#' the function chooses the one with the smallest within-segment squared-error
#' cost. The validity statistics are maintained incrementally in C++, so this
#' interface is considerably faster than supplying an R validity function to
#' [svp0()].
#'
#' A candidate segment is valid while its test statistic is strictly below its
#' threshold. The available values of `test` are:
#'
#' * `"gaussian_mean"`: Gaussian FOCUS likelihood-ratio test for a change in
#'   mean. Use this for independent Gaussian observations with constant
#'   variance.
#' * `"gamma_rate"`: likelihood-ratio test for a change in the rate of
#'   positive Gamma observations (unit shape in the current implementation).
#' * `"gaussian_variance"`: Gamma-rate test applied to squared observations,
#'   for changes in Gaussian variance around a known zero mean.
#' * `"AR1"`: exact fixed-`rho` Gaussian likelihood-ratio scan for a change in
#'   the marginal mean of an AR(1) series. `sigma2` is the innovation variance.
#' * `"AR1Profile"`: the same exact AR(1) scan, profiling out the innovation
#'   variance. This is useful when its scale is unknown.
#' * `"AR1Focus"`: faster approximate AR(1) test that applies Gaussian FOCUS
#'   to the innovations `x[t] - rho * x[t - 1]`. The exact `"AR1"` test is the
#'   preferred choice when boundary accuracy matters.
#'
#' The main pruning setting is `prune_after_if_unvalid = TRUE`: once a segment
#' beginning at a candidate boundary becomes invalid, that candidate is not
#' extended further. Setting `prune_before_if_invalid = TRUE` additionally
#' removes all older candidate boundaries when a later candidate fails. Thus
#' `TRUE/TRUE` is the most aggressive FOCUS pruning configuration. Set either
#' option to `FALSE` only when comparing pruning rules; doing so can retain more
#' candidates and increase run time.
#'
#' @param data Numeric vector containing the univariate series. Missing or
#'   non-finite values are not supported.
#' @param gamma Positive scalar validity threshold. A larger value accepts
#'   longer or less homogeneous segments and therefore generally produces
#'   fewer changes.
#' @param test Character scalar selecting one of the validity tests listed in
#'   Details. Defaults to `"gaussian_mean"`.
#' @param prune_after_if_unvalid Logical; discard a candidate boundary after
#'   its current segment fails the test.
#' @param prune_before_if_invalid Logical; when a candidate segment fails,
#'   also discard candidate boundaries older than its start.
#' @param sigma2 Positive finite innovation variance for the AR1 tests.
#' @param rho AR(1) coefficient for the three AR1 tests. It must be finite and
#'   strictly between -1 and 1. Use [AR1_rho()] to obtain a robust estimate if
#'   `rho` is unknown, it is estimated robustly from the full series.
#' @param profile_sigma Logical; profile the innovation variance when
#'   `test = "AR1"`. Using `test = "AR1Profile"` has the same effect.
#' @param quantile Quantile level used by `"quantile"` and
#'   `"quantileExact"`. It is ignored by other tests.
#'
#' @return A list with `changepoints` (the inclusive end of every segment,
#'   including `length(data)`), `lastIndexSet` (candidate boundaries remaining
#'   at termination), `nb` (candidate count at each time), `costQ` (currently
#'   `NULL`), and `R`. Row `t + 1` of matrix `R` stores the best cumulative
#'   squared-error cost, number of segments, and previous boundary at time `t`.
#'
#' @examples
#' set.seed(1)
#' x <- rep(c(0, 2, -1), each = 40) + rnorm(120)
#' SVP(x, gamma = 1.5 * log(length(x)))$changepoints
#'
#' # Aggressive TRUE/TRUE pruning:
#' SVP(x, gamma = 1.5 * log(length(x)), test = "gaussian_mean",
#'     prune_after_if_unvalid = TRUE,
#'     prune_before_if_invalid = TRUE)
#'
#' @seealso [svp0()] for arbitrary R validity functions, [AR1_rho()], and
#'   [AR1_single_change()].
#' @export
SVP <- function(data, gamma, test = "gaussian_mean", prune_after_if_unvalid = TRUE, prune_before_if_invalid = FALSE, sigma2 = 1.0, rho = NA_real_, profile_sigma = FALSE, quantile = 0.01) {
    .Call(`_svpChange2_SVP`, data, gamma, test, prune_after_if_unvalid, prune_before_if_invalid, sigma2, rho, profile_sigma, quantile)
}

#' Smallest Valid Partitioning with Validation and Pruning using Rcpp
#'
#' @title Smallest Valid Partitioning with Validation and Pruning
#' @description This function implements a dynamic programming approach to segment a univariate signal into the smallest number of valid segments, according to a user-defined validation function. Each segment must pass a validity test (e.g., based on variance, range, etc.). The algorithm minimizes a quadratic cost subject to this constraint.
#'
#' @param data A numeric vector representing the univariate signal to be segmented.
#' @param gamma A numeric value used as a threshold in the validation function and as a penalty for each segment.
#' @param test A function of the form `function(data, gamma)` returning TRUE if the segment is valid. Default is `valid_OP`.
#' @param prune_after_if_unvalid Logical. If TRUE (default), the algorithm applies *segment-wise validation*:
#' at each time step, it tests whether the candidate segment \code{data[(s+1):t]} is valid using the
#' user-defined function \code{test}. If the segment fails the test, the candidate \code{s} is removed
#' (pruned) from the set of possible changepoints. This accelerates computation by avoiding invalid
#' segment extensions. If FALSE, the algorithm skips this validation and considers all candidate
#' segments without checking their validity (which can be faster but may return invalid segments).
#' @param prune_if_PELT Logical.
#'
#' @return A list with the following components :
#' \describe{
#'   \item{changepoints}{Integer vector indicating the ending index of each segment (i.e., positions of changepoints).}
#'   \item{nb}{Integer vector of length \code{length(data)}. At each position \code{t}, it records the number of candidates tested.}
#'   \item{costQ}{Numeric vector of length \code{length(data)}. Quadratic cost value at each time step. Set to NULL as it is recorded into matrix R}
#'   \item{R}{A matrix of dimension \code{(length(data)+1) x 3} containing, for each time step :
#'     \describe{
#'       \item{Q}{cumulative cost}
#'       \item{K}{number of segments in Q}
#'       \item{s}{previous changepoint}
#'     }
#'   }
#' }
#'
#' @export
svp0 <- function(data, gamma, test, prune_after_if_unvalid = TRUE, prune_if_PELT = FALSE) {
    .Call(`_svpChange2_svp0`, data, gamma, test, prune_after_if_unvalid, prune_if_PELT)
}

AR1_rho <- function(data) {
    .Call(`_svpChange2_AR1_rho`, data)
}

AR1_single_change <- function(data, gamma, rho = NA_real_, sigma2 = 1.0, profile_sigma = FALSE) {
    .Call(`_svpChange2_AR1_single_change`, data, gamma, rho, sigma2, profile_sigma)
}

#' C++ SVP with SMUCE validity and constrained Gaussian cost
#' @param y Numeric observations.
#' @param q SMUCE threshold.
#' @param sigma2 Known Gaussian variance.
#' @return Integer segment-end indices.
svp_smuce_cpp <- function(y, q, sigma2 = 1.0) {
    .Call(`_svpChange2_svp_smuce_cpp`, y, q, sigma2)
}

